import { getCountryName } from '../data/countries';
import { supabase, isSupabaseConfigured } from './supabase';
import type { PlayerLeaderboardEntry, CountryLeaderboardEntry, LeaderboardResponse, PlayerProfile } from '../types/country';

const PLAYER_CACHE = 'squishyBread.players.cache.v1';
const COUNTRY_CACHE = 'squishyBread.countries.cache.v1';
const CACHE_MS = 45_000;
const mockPlayers: PlayerLeaderboardEntry[] = [];
const mockCountries: CountryLeaderboardEntry[] = [];
const now = () => new Date().toISOString();
const readCache = <T>(key: string): { entries: T[]; updatedAt: string } | null => { try { const cached = JSON.parse(localStorage.getItem(key) ?? 'null') as { entries: T[]; updatedAt: string } | null; return cached && Date.now() - Date.parse(cached.updatedAt) < 86_400_000 ? cached : null; } catch { return null; } };
const writeCache = <T>(key: string, response: { entries: T[]; updatedAt: string }) => { try { localStorage.setItem(key, JSON.stringify(response)); } catch { /* storage unavailable */ } };

export class CountryRankingService {
  private players: { response: LeaderboardResponse<PlayerLeaderboardEntry>; expires: number } | null = null;
  private countries: { response: LeaderboardResponse<CountryLeaderboardEntry>; expires: number } | null = null;
  async ensureAnonymousAuth(): Promise<string | null> { if (!supabase) return null; const session = (await supabase.auth.getSession()).data.session; if (session) return session.user.id; const result = await supabase.auth.signInAnonymously(); return result.data.user?.id ?? null; }
  async syncProfile(profile: PlayerProfile): Promise<boolean> { if (!supabase) return false; const authId = (await supabase.auth.getSession()).data.session?.user.id; if (!authId || authId !== profile.id) return false; const rpc = await supabase.rpc('sync_profile', { p_id: profile.id, p_username: profile.username, p_country_code: profile.countryCode, p_score: profile.score, p_high_score: profile.highScore, p_best_combo: profile.bestCombo, p_total_presses: profile.totalPresses }); if (!rpc.error) return true; const fallback = await supabase.from('profiles').upsert({ id: profile.id, username: profile.username, country_code: profile.countryCode, score: profile.score, best_combo: profile.bestCombo, total_presses: profile.totalPresses, updated_at: profile.updatedAt }, { onConflict: 'id' }); return !fallback.error; }
  invalidate(): void { this.players = null; this.countries = null; }
  async getPlayers(currentId: string, force = false, current?: { username: string; countryCode: string; score: number; bestCombo: number }): Promise<LeaderboardResponse<PlayerLeaderboardEntry>> { if (!force && this.players && this.players.expires > Date.now()) return this.players.response; if (!isSupabaseConfigured || !supabase) return this.players = this.mockPlayers(currentId, current), this.players.response; const query = await supabase.from('profiles').select('id,username,country_code,score,best_combo').order('score', { ascending: false }).limit(100); if (query.error) return this.cachedPlayers(currentId, query.error.message); const entries = (query.data ?? []).map((row, index) => ({ rank: index + 1, id: row.id, username: row.username, countryCode: row.country_code, score: Number(row.score), bestCombo: row.best_combo })); const playerRank = entries.find((entry) => entry.id === currentId)?.rank ?? await this.playerRank(currentId); const response = { entries, playerRank, updatedAt: now(), source: 'supabase' as const }; this.players = { response, expires: Date.now() + CACHE_MS }; writeCache(PLAYER_CACHE, response); return response; }
  async getCountries(currentCode: string, force = false, currentScore = 0): Promise<LeaderboardResponse<CountryLeaderboardEntry>> { if (!force && this.countries && this.countries.expires > Date.now()) return this.countries.response; if (!isSupabaseConfigured || !supabase) return this.countries = this.mockCountries(currentCode, currentScore), this.countries.response; const query = await supabase.from('country_leaderboard').select('country_code,total_score,player_count,rank').order('rank', { ascending: true }).limit(100); if (query.error) return this.cachedCountries(currentCode, query.error.message); const entries = (query.data ?? []).map((row) => ({ rank: Number(row.rank), countryCode: row.country_code, totalScore: Number(row.total_score), playerCount: Number(row.player_count), updatedAt: now() })); const own = entries.find((entry) => entry.countryCode === currentCode)?.rank ?? await this.countryRank(currentCode); const response = { entries, playerRank: own, updatedAt: now(), source: 'supabase' as const }; this.countries = { response, expires: Date.now() + CACHE_MS }; writeCache(COUNTRY_CACHE, response); return response; }
  private mockPlayers(currentId: string, current?: { username: string; countryCode: string; score: number; bestCombo: number }) { const response: LeaderboardResponse<PlayerLeaderboardEntry> = { entries: [...mockPlayers, { rank: 6, id: currentId, username: current?.username || 'You', countryCode: current?.countryCode || 'TH', score: current?.score || 0, bestCombo: current?.bestCombo || 0 }], playerRank: 1, updatedAt: now(), source: 'mock' }; this.players = { response, expires: Date.now() + CACHE_MS }; return this.players; }
  private mockCountries(currentCode: string, currentScore: number) { const entries = [{ rank: 1, countryCode: currentCode || 'TH', totalScore: currentScore, playerCount: 1 }]; const response: LeaderboardResponse<CountryLeaderboardEntry> = { entries, playerRank: entries.find((entry) => entry.countryCode === currentCode)?.rank, updatedAt: now(), source: 'mock' }; this.countries = { response, expires: Date.now() + CACHE_MS }; return this.countries; }
  private cachedPlayers(currentId: string, error: string): LeaderboardResponse<PlayerLeaderboardEntry> { const cached = readCache<PlayerLeaderboardEntry>(PLAYER_CACHE); const response = cached ? { entries: cached.entries, playerRank: cached.entries.find((entry) => entry.id === currentId)?.rank, updatedAt: cached.updatedAt, source: 'cache' as const, error } : { entries: [], updatedAt: now(), source: 'cache' as const, error }; this.players = { response, expires: Date.now() + CACHE_MS }; return response; }
  private cachedCountries(currentCode: string, error: string): LeaderboardResponse<CountryLeaderboardEntry> { const cached = readCache<CountryLeaderboardEntry>(COUNTRY_CACHE); const response = cached ? { entries: cached.entries, playerRank: cached.entries.find((entry) => entry.countryCode === currentCode)?.rank, updatedAt: cached.updatedAt, source: 'cache' as const, error } : { entries: [], updatedAt: now(), source: 'cache' as const, error }; this.countries = { response, expires: Date.now() + CACHE_MS }; return response; }
  private async playerRank(id: string): Promise<number | undefined> { if (!supabase) return undefined; const result = await supabase.rpc('get_player_rank', { p_id: id }); return result.error ? undefined : Number(result.data); }
  private async countryRank(code: string): Promise<number | undefined> { if (!supabase) return undefined; const result = await supabase.rpc('get_country_rank', { p_country_code: code }); return result.error ? undefined : Number(result.data); }
}
